#!/bin/sh

# Copy to .git/hooks/ to use.

set -e

if git diff-index --check --cached HEAD >/dev/null 2>&1 ;
then
    :
else
    2>&1 echo "Auto fixing whitespace issues..."

    TEMP=$(mktemp)
    # We fix whitespace in the index and in the working tree
    # separately to preserve non-added changes.
    git diff-index -p --cached HEAD > "$TEMP"
    git apply --cached -R "$TEMP"
    git apply --cached --whitespace=fix "$TEMP"

    git diff-index -p HEAD > "$TEMP"
    git apply -R "$TEMP"
    git apply --whitespace=fix "$TEMP"
    rm "$TEMP"

    # Check that we did fix whitespace
    if git diff-index --check --cached HEAD;
    then
        :
    else
        2>&1 echo "Auto-fixing whitespace failed: errors remain."
        2>&1 echo "This may fix itself if you try again."
        2>&1 echo "(Consider whether the number of errors decreases after each run.)"
        exit 1
    fi
    2>&1 echo "Whitespace issues fixed!"
fi
