#!/bin/sh

# Copy to .git/hooks/ to use.

set -e

CODE=0
for f in $(git diff --cached --name-only)
do
    if [ -e "$f" ] && dev/tools/should-check-whitespace.sh "$f"
    then
        dev/tools/check-eof-newline.sh "$f" || CODE=1
        dev/tools/fix-eof-newline.sh "$f"
    fi
done

if [ $CODE -ne 0 ]
then
    2>&1 echo "Some files had newline errors; they have been fixed in the working tree."
    2>&1 echo "Make sure to add them before committing."
    2>&1 echo "This may fix itself if you were using git commit -a, and you try again."
    exit 1
fi

if git diff-index --check --cached HEAD >/dev/null 2>&1 ;
then
    :
else
    2>&1 echo "Auto fixing whitespace issues..."

    TEMP=$(mktemp)
    # We fix whitespace in the index and in the working tree
    # separately to preserve non-added changes.
    git diff-index -p --cached HEAD > "$TEMP"
    git apply --cached -R "$TEMP"
    git apply --cached --whitespace=fix "$TEMP"

    git diff-index -p HEAD > "$TEMP"
    git apply -R "$TEMP"
    git apply --whitespace=fix "$TEMP"
    rm "$TEMP"

    # Check that we did fix whitespace
    if git diff-index --check --cached HEAD;
    then
        :
    else
        2>&1 echo "Auto-fixing whitespace failed: errors remain."
        2>&1 echo "This may fix itself if you try again."
        2>&1 echo "(Consider whether the number of errors decreases after each run.)"
        exit 1
    fi
    2>&1 echo "Whitespace issues fixed!"
fi
